Local storage
Unyielding1/Portfolio-pair-programing pull request #9
Opened 2022-05-12 16:24 UTC by Unyielding1

Add Local storage to the Input Form
Update all.js files.
Install ESlint on project

2022-05-12 17:35 UTC, Ismailco requested changes
### Hi @Unyielding1,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Used Github Flow
✔️ Work documented professionally
✔️ The form behave as expected

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 17:35 UTC, Ismailco commented on oops.min.js
> +/* eslint-disable no-unused-vars */
- [ ] Please don't ignore linters, you can try to fix them instead

2022-05-12 17:35 UTC, Ismailco commented on oops.min.js
> +function Oops(a) {
- [ ] The form data for all inputs should be stored in a single object, and saved to a single local storage registry, please implement this feature so your code meets the requirements

2022-05-12 17:35 UTC, Ismailco commented on oops.min.js
> +        console.warn('oops.js warn: '+e+' is not available.'); return false;
- [ ] For best practice please consider not committing  ```console.warn``` or ```console.log``` to your repo it makes the code looks messy.

2022-05-12 17:35 UTC, Ismailco commented on oops.min.js
> +function Oops(a) {
- [ ] Your code look's too messy, if you can please consider using a non minified code so the code reviewer can check your code more easily

2022-05-12 17:35 UTC, Ismailco commented on README.md
- [ ] [Optional] Your README needs some modification to look more professional, kindly consider changing the name to a meaningful one

2022-05-12 21:35 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @Unyielding1, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 21:35 UTC, sja-thedude commented on form.js
> +
- [ ] As suggested by the previous reviewer, Kindly make sure that the form data for all inputs should be stored in a single object, and saved to a single local storage registry.

```
const formData = {
    name: nameInput.value,
    email: emailInput.value,
    body: bodyInput.value,
};
```

2022-05-12 21:35 UTC, sja-thedude commented on form.js
> +});
- [ ] Kindly make sure that when the user loads the page, the code checks if there are any saved data in the local storage, and if so the input fields are pre-filled with the data. 
( _When the user refreshes the browser the data in the form should be persistent and to make it so you can follow the code below_ )

```
window.onload = () => {
  let savedFormData = localStorage.getItem('contactFormInput');
  savedFormData = JSON.parse(savedFormData);
  // Check if the form data object is found on localStorage
  if (savedFormData) {
  // populate inputs values if data was found
  // ex: nameInput.value = savedFormData.name
  }
};
```

2022-05-13 01:37 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 20:15 UTC, merged